# Generated by Django 5.2.13 on 2026-04-28 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price_eur', models.DecimalField(decimal_places=2, max_digits=8)),
                ('supplier_url', models.URLField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(default='other', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DroneCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('stl', 'File STL'), ('bom', 'Bill of Materials'), ('firmware', 'Configurazione Firmware'), ('wiring', 'Schema Cablaggio'), ('assembly', 'Guida Assemblaggio'), ('image', 'Immagine'), ('video_url', 'Video URL'), ('other', 'Altro')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='projects/')),
                ('external_url', models.URLField(blank=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_documentation', models.IntegerField()),
                ('rating_difficulty_accuracy', models.IntegerField()),
                ('rating_performance', models.IntegerField()),
                ('comment', models.TextField()),
                ('build_photos', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DroneProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('pending_validation', 'In validazione'), ('pending_review', 'In revisione'), ('published', 'Pubblicato'), ('suspended', 'Sospeso'), ('rejected', 'Rifiutato')], default='draft', max_length=30)),
                ('license_type', models.CharField(choices=[('open_source', 'Open Source'), ('open_royalty', 'Open con Royalty'), ('commercial', 'Commerciale'), ('university', 'Universitario')], default='open_royalty', max_length=20)),
                ('royalty_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('difficulty', models.CharField(choices=[('basic', 'Base'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzato')], default='basic', max_length=20)),
                ('estimated_weight_grams', models.IntegerField(default=0)),
                ('estimated_flight_time_minutes', models.IntegerField(default=0)),
                ('max_payload_grams', models.IntegerField(default=0)),
                ('operating_range_km', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('use_cases', models.JSONField(default=list)),
                ('estimated_print_cost_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_print_cost_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_print_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_total_cost_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_total_cost_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('easa_category', models.CharField(blank=True, max_length=50)),
                ('compliance_notes', models.TextField(blank=True)),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('order_count', models.IntegerField(default=0)),
                ('fork_count', models.IntegerField(default=0)),
                ('flag_count', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('is_university_project', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.dronecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
