# Generated by Django 5.2.13 on 2026-04-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('evidence_urls', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('open', 'Aperta'), ('under_review', 'In revisione'), ('resolved_refund', 'Risolta con rimborso'), ('resolved_reprint', 'Risolta con ristampa'), ('closed', 'Chiusa')], default='open', max_length=30)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('kit', 'Kit da assemblare'), ('assembled', 'Prodotto assemblato')], default='kit', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'In attesa pagamento'), ('payment_confirmed', 'Pagamento confermato'), ('assigned_print', 'Assegnato a nodo stampa'), ('printing', 'In stampa'), ('print_done', 'Stampa completata'), ('assigned_assembly', 'Assegnato a centro assemblaggio'), ('assembling', 'In assemblaggio'), ('testing', 'In test'), ('shipped', 'Spedito'), ('delivered', 'Consegnato'), ('disputed', 'In disputa'), ('cancelled', 'Annullato'), ('refunded', 'Rimborsato')], default='pending', max_length=30)),
                ('quantity', models.IntegerField(default=1)),
                ('is_fast_track', models.BooleanField(default=False)),
                ('design_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('print_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('components_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('assembly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fast_track_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('components_margin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stripe_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100)),
                ('stripe_transfer_ids', models.JSONField(default=dict)),
                ('shipping_address', models.JSONField(default=dict)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('tracking_url', models.URLField(blank=True)),
                ('courier', models.CharField(blank=True, max_length=50)),
                ('insurance_included', models.BooleanField(default=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
