# Generated by Django 5.2.13 on 2026-04-29 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('website', models.URLField(blank=True)),
                ('default_supplier_url', models.URLField(blank=True, help_text='URL fornitore default (può contenere affiliate ID).')),
                ('categories', models.JSONField(default=list, help_text='Categorie BOM in cui questo brand è rilevante (motor, esc, fc, …).')),
                ('is_partner', models.BooleanField(default=False, help_text='Accordo commerciale attivo.')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['-is_partner', 'sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='bomitem',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_uses', to='marketplace.brand'),
        ),
    ]
