# Generated by Django 5.2.13 on 2026-04-28 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('passed', 'Superata'), ('failed', 'Fallita'), ('warning', 'Con avvisi')], default='pending', max_length=20)),
                ('is_printable', models.BooleanField(default=False)),
                ('min_wall_thickness_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('has_open_surfaces', models.BooleanField(default=False)),
                ('has_non_manifold', models.BooleanField(default=False)),
                ('overhang_angle_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estimated_print_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_filament_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('issues', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('raw_report', models.JSONField(default=dict)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='marketplace.droneproject')),
            ],
            options={
                'ordering': ['-validated_at'],
            },
        ),
    ]
