from .base import *  # noqa

DEBUG = False
USE_S3 = True
EMAIL_BACKEND = 'django_ses.SESBackend'

SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
